name: 'Recognize Vulnerability Report'
description: 'Create a report of the vulnerabilities that are found and add it as a comment to a pull request.'
inputs:
  token:
    description: 'GitHub API token'
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}
runs:
  using: 'node12'
  main: 'dist/index.js'
