name: 'Build & Test action'
on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - 'releases/*'
      - TD-239_2

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm --version
          node --version
          npm install
      - run: |
          npm run all
